# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e19c8204d33df2ea92041e7c8010e8975b2ede6a1f5541076622e606bd37791d3513bb5179e28d2eb29e4d7dc51e54bfcc7568a7a2527070fb0b7dcd23304623

test:
  secret_key_base: 45a718eaa8346aa6dba40a5aeffec204c04334a5edfd72be5bb445cfb42af90cb5860800a6867f302b5c7db9bd4e187969b767099b9363254a70cdc0d2b26a56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
